### ISSUE TITLE
idle_in_transaction_session_timeout manually set to "3s" breaks state refreshing

### ISSUE THREAD

**Issue by mdespriee** [cyrilgdn/terraform-provider-postgresql#102]
`idle_in_transaction_session_timeout` has been manually set on a role (in an emergency), using
`ALTER ROLE reader SET idle_in_transaction_session_timeout='3s';` which is a valid command and format for postgresql.

Unfortunately, this later broke terraform when refreshing, with the following error:
`Error: Error reading statement_timeout: strconv.Atoi: parsing "3s": invalid syntax`

Note that per postgresql hints, valid units for this parameter are "us", "ms", "s", "min", "h", and "d" 

Manually altering the value to `3000` solved the problem.

### Terraform Version

```
Terraform v0.14.4
+ provider registry.terraform.io/cyrilgdn/postgresql v1.13.0
+ provider registry.terraform.io/hashicorp/aws v3.48.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### Affected Resource(s)

```
resource "postgresql_role" "tsdb_reader" {
  provider            = postgresql.tsdb
  name                = "reader"
  login               = true
  password            = data.aws_ssm_parameter.tsdb_reader_pwd.value
  skip_reassign_owned = true
}
```

### Debug Output
Sorry, too much sensitive stuff in there

**Comment by cyrilgdn** [comment]
Hi, 

Thanks for opening this issue.

This is the same problem than #96 , I added in v v1.13.0 a new lock system in the provider to make it faster but it uses Postgresql query which is impacted by the different timeout (I didn't think about it when I added it :man_facepalming: )

I'll see how to fix it, meanwhile you can use v1.12.0 which does not use the lock system and it should work.
