### ISSUE TITLE
postgresql_grant.privileges gets plans as if not applied

### ISSUE THREAD

**Issue by maxiaohao** [cyrilgdn/terraform-provider-postgresql#106]
### Terraform Version
v0.14.3

### Provider Version
1.13.0

### postgres server version
11.x (cloudsql in GCP)

### Affected Resource(s)
postgresql_grant

### Terraform Configuration Files
```hcl
resource "postgresql_grant" "ads" {
  for_each    = local.email_to_privileges
  database    = "db_ads"
  role        = each.key
  schema      = var.ads_schmea
  object_type = "table"
  privileges  = each.value
  provider    = postgresql.ads
}
```

### Expected Behavior
The `postgresql_grant` to be applied and next terraform plans should be all clear. 

### Actual Behavior
After apply, when doing a few `terraform plan`s we get a clear one which is good, but after a short while (normally 10 minutes) if we do the plan again, we get some unexpected plan saying it is going to change an empty `privileges` to the values we define in code. 
![image](https://user-images.githubusercontent.com/4846119/126930208-dd8751af-b859-48cd-9da1-a940a97dd702.png)
But by verifying the actual permissions, all those privileges have been successfully applied into the db. 

### Steps to Reproduce
For now we have to ignore changes on it, like
```
  lifecycle {
    ignore_changes = [
      privileges,
    ]
  }
```

**Comment by cyrilgdn** [comment]
Hi @maxiaohao ,

Thanks for opening this issue.

Just to confirm, are new tables created between the first apply and the first dirty plan?
The provider checks that all the tables in the specified schema have the expected privileges. It will provide this plan this diff if any table does'nt have it.

**Comment by maxiaohao** [comment]
@cyrilgdn Thanks for your reply, and yes chances were some table creation in the middle. 
That would would explain it. 
Before I close this ticket, I'd just to check with you if there is any plan around doing something like altering `DEFAULT PRIVILEGES` as an improvement to have the grants more smoothly for new tables?

**Comment by cyrilgdn** [comment]
@maxiaohao There's a [`postgresql_default_privileges`](https://registry.terraform.io/providers/cyrilgdn/postgresql/latest/docs/resources/postgresql_default_privileges) resource in the provider for that.

You can easily create a module that creates both resources for the same database/schema.

**Comment by maxiaohao** [comment]
Awesome! Will definitely look into that. 
Thanks much for your advice! @cyrilgdn 
I am closing this ticket now.
