### ISSUE TITLE
Validate privileges in postgresql_grant

### ISSUE THREAD

**Issue by Herrmlo** [cyrilgdn/terraform-provider-postgresql#121]
Hi, 
I've got a feature request when using postgresql_grant to validate the privileges.

### Terraform Version
```
Terraform v1.0.4
on windows_amd64
+ provider registry.terraform.io/cyrilgdn/postgresql v1.12.0
+ provider registry.terraform.io/hashicorp/azurerm v2.68.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### Affected Resource
- postgresql_grant

### Expected Behavior
When using following example 
```terraform
resource "postgresql_grant" "psql_grant_table" {
  role     = postgresql_role.psql_role.name
  database = var.database_name
  schema   = postgresql_schema.psql_schema.name
  object_type = "table"
  privileges  = ["SELECT", "INSERT", "CREATE", "CONNECT"]
}
```
`terraform plan` should notify me that `CREATE` and `CONNECT` are invalid privileges.

### Actual Behavior
`terraform plan` shows that it will create the resource with the invalid privileges and fails when executing `terraform apply`.

**Comment by cyrilgdn** [comment]
Hi,

Unfortunately it's not possible to validate fields value that depends on another field in Terraform (cf https://github.com/hashicorp/terraform-plugin-sdk/issues/233)

During the plan, there would be a possibility to use some advanced Terraform SDK functions to do that but I think it's too much code for what it brings.
Note that we validate the privileges during apply before trying to really grant, so it fails before trying to connect to Postgres.

I allow myself to close this issue as won't fix for now. If multi-fields validation is possible at some point, we'll implement that.
