### ISSUE TITLE
pq: got 3 parameters but the statement requires 2

### ISSUE THREAD

**Issue by p4cket** [cyrilgdn/terraform-provider-postgresql#13]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
root@salt:~/terraform/psql_admins# terraform -v
Terraform v0.13.5
+ provider registry.terraform.io/cyrilgdn/postgresql v1.8.1
+ provider registry.terraform.io/hashicorp/aws v3.16.0
+ provider registry.terraform.io/hashicorp/external v2.0.0
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.3
+ provider registry.terraform.io/hashicorp/local v2.0.0
+ provider registry.terraform.io/hashicorp/random v3.0.0

### Affected Resource(s)
Please list the resources as a list, for example:
- postgresql_grant

### Terraform Configuration Files
```hcl
resource "postgresql_grant" "readwrite_dbs" {
  for_each = data.external.dbs.result

  database    = each.key
  role        = postgresql_role.rw-role.name
  schema      = "public"
  object_type = "database"
  privileges  = ["CONNECT"]
}

resource "postgresql_grant" "readwrite_tables" {
  for_each = data.external.dbs.result

  database    = each.key
  role        = postgresql_role.rw-role.name
  schema      = "public"
  object_type = "table"
  privileges  = ["SELECT", "INSERT", "UPDATE", "DELETE", "TRUNCATE", "REFERENCES", "TRIGGER"]
}

resource "postgresql_grant" "readwrite_sequence" {
  for_each = data.external.dbs.result

  database    = each.key
  role        = postgresql_role.rw-role.name
  schema      = "public"
  object_type = "sequence"
  privileges  = ["USAGE", "SELECT", "UPDATE"]
}

resource "postgresql_grant" "readwrite_function" {
  for_each = data.external.dbs.result

  database    = each.key
  role        = postgresql_role.rw-role.name
  schema      = "public"
  object_type = "function"
  privileges  = ["EXECUTE"]
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
no syntax error  👍 

### Actual Behavior
sql syntax error

```Error: pq: got 3 parameters but the statement requires 2



Error: pq: got 3 parameters but the statement requires 2



Error: pq: got 3 parameters but the statement requires 2



Error: pq: got 3 parameters but the statement requires 2



Error: pq: got 3 parameters but the statement requires 2



Error: pq: got 3 parameters but the statement requires 2



Error: pq: got 3 parameters but the statement requires 2



Error: pq: got 3 parameters but the statement requires 2



Error: pq: got 3 parameters but the statement requires 2



Error: pq: got 3 parameters but the statement requires 2```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`


### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- this merge request bring issue: https://github.com/cyrilgdn/terraform-provider-postgresql/commit/3071ecc51eb2945eecd9eb16d7c0f82c29e70847

**Comment by paul-pop** [comment]
Any chance we can backport this to 1.8.x?
