### ISSUE TITLE
Need to use connection pooling or something to prevent connection exhaustion 

### ISSUE THREAD

**Issue by red8888** [cyrilgdn/terraform-provider-postgresql#131]
```
Terraform v0.14.11
+ provider registry.terraform.io/cyrilgdn/postgresql v1.14.0
+ provider registry.terraform.io/hashicorp/aws v3.56.0
+ provider registry.terraform.io/hashicorp/google v3.65.0
+ provider registry.terraform.io/hashicorp/google-beta v3.82.0
+ provider registry.terraform.io/hashicorp/http v2.1.0
```

I want to be able to do things like loop over all my DBs and apply permissions, but this provider is slamming my instance with concurrent connections. Seems like _every_ resource creates its own connection!?

I only have a few DBs, but pretty soon I wasn't even able to run plan without this provider spawning 80+ connections. This means I might have to bump up my max connections really high just to support this provider.

It should support connection pooling or something prevent this otherwise it won't be useable for non-trivially sized infra.

**Comment by cyrilgdn** [comment]
Hi @red8888 ,

Thanks for opening this issue.

There's is per database [connection limit](https://registry.terraform.io/providers/cyrilgdn/postgresql/latest/docs#max_connections) (which is 20 per default) so you may want to decrease it.

Let me know if it's enough.

**Comment by red8888** [comment]
wow can't believe I missed that. Yup thats all I was looking for.

So if I set max_connections to 2 and Im looping over 15 DBs it will only open a max of 30 connections?
