### ISSUE TITLE
Is there a way to do per-table permisisons?

### ISSUE THREAD

**Issue by richstokes** [cyrilgdn/terraform-provider-postgresql#137]
Trying to do something like this, but no luck:

```
resource "postgresql_grant" "table-user-perms" {
  provider    = xxx
  database    = xxx  
  role        = "user-name"
  schema      = "public.table_name_here"
  object_type = "table"
  privileges  = ["SELECT"]
}
```

Gives:
`Error: could not find schema 'public.table_name_here' while looking for owner`

**Comment by kostiantyn-nemchenko** [comment]
The following example should work:
```
resource "postgresql_grant" "table-user-perms" {
  provider    = xxx
  database    = xxx  
  role        = "user-name"
  schema      = "public"
  objects     = ["table_name_here"]
  object_type = "table"
  privileges  = ["SELECT"]
}
```

This example assumes the [1.14.0](https://github.com/cyrilgdn/terraform-provider-postgresql/blob/master/CHANGELOG.md#1140-august-22-2021) version of the provider.

**Comment by richstokes** [comment]
Thanks, that was it - upgrading to 1.14.0 fixed it
