### ISSUE TITLE
Not able to create role on azure "Azure Database for PostgreSQL server"

### ISSUE THREAD

**Issue by hadiulla** [cyrilgdn/terraform-provider-postgresql#156]
### Terraform Version
1.0.8

### Terraform Configuration Files
```hcl
provider "postgresql" {
  host            = "pkpxcbudgv.postgres.database.azure.com"
  port            = 5432
  database        = "my-db-090"
  username        = "auopygnyva@pkpxcbudgv"
  password        = "PASSWORD_HERE"
  sslmode         = "require"
  connect_timeout = 15
}

resource "postgresql_role" "my_user_role" {
  name             = "test_user_role@pkpxcbudgv"
  }
```

### Expected Behavior
Should be able to connect to server and create role.

### Actual Behavior
`Error: error detecting capabilities: error PostgreSQL version: pq: password authentication failed for user "auopygnyva"`

### Steps to Reproduce
1. `terraform apply`

**Comment by cyrilgdn** [comment]
Hi @hadiulla ,

Is your SQL database linked to an Active Directory for authentication?

If no, you should not add the `@pkpxcbudgv` part in the username.
(I just created a simple Postgresql database on Azure with `postgres` as admin username and I just need to set `username = "postgres"` in the Terraform configuration)

If yes, you may need to set the `database_username` setting too, for example, with a database created with Terraform, configuration looks like:
```hcl
provider "postgresql" {
  host = azurerm_postgresql_server.postgres.fqdn
  port = 5432
  database = azurerm_postgresql_database.postgres.name
  username = format( "%s@%s", azurerm_postgresql_server.postgres.administrator_login, azurerm_postgresql_server.postgres.fqdn )
  database_username = azurerm_postgresql_server.postgres.administrator_login
  password = azurerm_postgresql_server.postgres.administrator_login_password
  sslmode = "require"
  superuser = false
}
```

Let me know if it helps!

**Comment by hadiulla** [comment]
![image](https://user-images.githubusercontent.com/12107091/140760369-3ec2687b-4889-4c8e-87de-853801645236.png)
Hi @cyrilgdn 
thanks for responding.
No, this is not linked to AD authentication, hence i removed `@hostname` in the host. Still same error as attached in the screenshot.

**Comment by cyrilgdn** [comment]
@hadiulla  According to your screenshot and your initial message, you removed the username (`auopygnyva`) instead of the hostname (`pkpxcbudgv`)

This should be:
```hcl
provider "postgresql" {
  host            = "pkpxcbudgv.postgres.database.azure.com"
  port            = 5432
  database        = "my-db-090"
  username        = "auopygnyva"
  password        = "PASSWORD_HERE"
  sslmode         = "require"
  connect_timeout = 15
}
```

You can first test it with:
```bash
psql "host=pkpxcbudgv.postgres.database.azure.com port=5432 dbname=my-db-090 user=auopygnyva sslmode=require"
```

**Comment by hadiulla** [comment]
This works fine, apologies, password was incorrect. Got it working after changing password.
