### ISSUE TITLE
Error: Current username is used as role name

### ISSUE THREAD

**Issue by ingokuba** [cyrilgdn/terraform-provider-postgresql#172]
### Terraform Version
1.1.2

### Affected Resource(s)
- postgresql_database

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    postgresql = {
      source  = "cyrilgdn/postgresql"
      version = "1.14.0"
    }
  }
}

provider "postgresql" {
  host      = "example.postgres.database.azure.com"
  username  = "psqladmin@example"
  password  = "example123"
  superuser = false
}

resource "postgresql_role" "dummie" {
  name     = "dummie"
  password = "example123"
  login    = true
}

resource "postgresql_database" "example-db" {
  name  = "example-db"
  owner = "dummie"
}
```

### Debug Output
```
postgresql_database.example-db: Creating...
2022-01-04T12:51:51.852+0100 [INFO]  Starting apply for postgresql_database.example-db
2022-01-04T12:51:51.852+0100 [DEBUG] postgresql_database.example-db: applying the planned Create change
2022-01-04T12:51:54.307+0100 [DEBUG] provider.terraform-provider-postgresql_v1.14.0: 2022/01/04 12:51:54 grantRoleMembership: granting dummie to psqladmin@example
2022-01-04T12:51:54.963+0100 [ERROR] vertex "postgresql_database.example-db" error: Error granting role dummie to psqladmin@example: pq: role "psqladmin@example" does not exist
╷
│ Error: Error granting role dummie to psqladmin@example: pq: role "psqladmin@example" does not exist
│ 
│   with postgresql_database.example-db,
│   on schema.tf line 41, in resource "postgresql_database" "example-db":
│   41: resource "postgresql_database" "example-db" {
```

### Expected Behavior
Created database in Azure Database for PostgreSQL server with given owner.

### Actual Behavior
Database creation fails, because username `currentUser` from provider configuration is taken as role name.

See https://github.com/cyrilgdn/terraform-provider-postgresql/blob/master/postgresql/resource_postgresql_database.go#L135

The `@{servername}` should be removed when using the `currentUser` as role name.

**Comment by cyrilgdn** [comment]
@ingokuba You have the [`database_username`](https://registry.terraform.io/providers/cyrilgdn/postgresql/latest/docs#database_username) setting in the provider to solve this problem:

```hcl
provider "postgresql" {
  host      = "example.postgres.database.azure.com"
  username  = "psqladmin@example"
  database_username = "psqladmin"
  password  = "example123"
  superuser = false
}
```

We cannot just split on `@` like you did in #173 as it's a format specific to Azure. 
You can have any format with [username maps](https://www.postgresql.org/docs/current/auth-username-maps.html)

I close this issue and PR #173  but feel free to comment or open it back if it does not work for you.

**Comment by ingokuba** [comment]
Yes, this works. Pardon my ignorance of this setting.
