### ISSUE TITLE
postgresql_role docs page leads to a 404

### ISSUE THREAD

**Issue by quixoticotech** [cyrilgdn/terraform-provider-postgresql#18]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

### Affected Resource(s)
Please list the resources as a list, for example:
- Documentation
https://registry.terraform.io/providers/cyrilgdn/postgresql/latest/docs/resources/postgresql_role

```
Note:

All arguments including role name and password will be stored in the raw state as plain-text. Read more about sensitive data in state.
```
If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
N/A

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
What should have happened?
The link should go to the sensitive data in terraform state page. But that seems to no longer exist at the previous link. It should probably go to https://www.terraform.io/docs/state/sensitive-data.html.

### Actual Behavior
What actually happened?
The link directs to https://registry.terraform.io/docs/state/sensitive-data which returns a 404 error page.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Go to [postgresql_role](https://registry.terraform.io/providers/cyrilgdn/postgresql/latest/docs/resources/postgresql_role).
2. Click on the [Read more about sensitive data in state.](https://registry.terraform.io/docs/state/sensitive-data) link in the `Note` section about sensitive data.

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?
No

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
No

**Comment by cyrilgdn** [comment]
Hi @quixoticotech ,

Thanks for reporting! Fixed in #22
