### ISSUE TITLE
Ability to grant permissions on a specific column

### ISSUE THREAD

**Issue by omarish** [cyrilgdn/terraform-provider-postgresql#185]
Hi, I'd like to grant permissions to a specific table column. I can do this in plain SQL like so:

```sql
GRANT update(column_name) on table_name TO "user"
```

When I tried running this with the provider, I tried granting the permission `UPDATE(column_name)`.

**Comment by cyrilgdn** [comment]
Hi, 
There's an open PR for that: https://github.com/cyrilgdn/terraform-provider-postgresql/pull/135

**Comment by omarish** [comment]
Got it, thanks!
