### ISSUE TITLE
Add support for foreign server and user mapping

### ISSUE THREAD

**Issue by bilby91** [cyrilgdn/terraform-provider-postgresql#198]
Hello,

We are using the provider very extensively in my organization and we are looking into managing foreign servers and user mappings. 

Foreign Server: https://www.postgresql.org/docs/current/sql-createserver.html
User Mapping: https://www.postgresql.org/docs/current/sql-createusermapping.html

I'm looking into potentially implementing it based on availability. Would this be something that the maintainers would like to support?

Thanks in advance for the hard work on this project!

**Comment by fabiopaiva** [comment]
Anyone working on this? It would be really nice to have this feature available
