### ISSUE TITLE
Can't create an Azure Single PostgreSql server user

### ISSUE THREAD

**Issue by Kosta-K** [cyrilgdn/terraform-provider-postgresql#206]
Hi there,

Thank you for opening an issue. Please provide the following information:

### Terraform Version
1.1.8

### Affected Resource(s)
Please list the resources as a list, for example:
- provider "postgresql"
- resource "postgresql_role"

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
provider "postgresql" {
  host            = data.azurerm_postgresql_server.pgsql_server.fqdn
  port            = 5432
  #database        = "postgres"
  username        = "pgsqltestadmin@pgsql-test-aue" 
  password        = var.pgsql.admin_secret  
  sslmode         = "require"
  connect_timeout = 15
  superuser       = false # https://github.com/hashicorp/terraform-provider-postgresql/issues/77
}
resource "postgresql_role" "mapp_role" {
  name = var.mapp.postgresql_user_name
  login    = true
  password = var.mapp.postgres_user_password
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

(https://gist.github.com/Kosta-K/04aa446b81c73959d97e76fc21eb490e)

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
New user in postgres server to be created.

### Actual Behavior
It errors with: 
Error: error detecting capabilities: error PostgreSQL version: pq: empty password returned by client
when  "superuser       = false "
It errors with:
Error: could not read role password from Postgres as connected user pgsqltestadmin@pgsql-test-aue is not a SUPERUSER. You can set `superuser = false` in the provider configuration so it will not try to read the password from Postgres
when "superuser       = true"

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Azure Single PostgreSql server with private endpoint network and public network connection disabled

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- https://github.com/hashicorp/terraform-provider-postgresql/issues/77   this one looks like pretty much the same, but AWS related.

**Comment by cyrilgdn** [comment]
Hi,

For Azure you also have to provide [`database_username`](https://registry.terraform.io/providers/cyrilgdn/postgresql/latest/docs#database_username) in the provider configuration (in your example, probably `database_username = "pgsqltestadmin"`) as the role name in Postgres is not the same than the login.

I allow myself to close this issue but feel free to comment or open it back if it does not solve your problem or if you are further questions.
