### ISSUE TITLE
Connect to cloud instances natively

### ISSUE THREAD

**Issue by ademariag** [cyrilgdn/terraform-provider-postgresql#21]
Hi,

in the previous repository there was an open feature request https://github.com/hashicorp/terraform-provider-postgresql/issues/110 to allow to natively connect to cloud instances like Cloud SQL Proxy for GCP and AWS/Azure equivalent.

@benfdking implemented that feature in their fork here: https://github.com/tumelohq/terraform-provider-postgresql/ using https://gocloud.dev/.

Would you consider such approach if I were to submit a patch? I am waiting on https://github.com/cyrilgdn/terraform-provider-postgresql/pull/5 first before I start working on it.

# References
https://github.com/benfdking/terraform-provider-postgresql/pull/1
https://gocloud.dev/howto/sql/

**Comment by cyrilgdn** [comment]
Hi @ademariag,

Thanks for opening this issue.

I don't really know `gocloud.dev` yet but if I understood correctly this just requires to add this dependency and just to change `postgres://` by `gcppostgres://` or similar no? (so add a scheme setting basically)

Yes, it could be interesting to support it if gocloud can helps to simplify connection to cloud providers.

I hope to be able to finish/release #5 this week.

**Comment by ademariag** [comment]
Just added the following draft PR: https://github.com/cyrilgdn/terraform-provider-postgresql/pull/24
Waiting on when you merge #5 

All credit to benfdking

**Comment by ademariag** [comment]
Already published and tested here: https://registry.terraform.io/providers/ademariag/postgresql/latest

**Comment by cyrilgdn** [comment]
Thanks, I merged #5 but it closed your draft PR (base branch has been deleted), could you open it back on master please?
