### ISSUE TITLE
Inconsistent Terraform state with postgresql_grant

### ISSUE THREAD

**Issue by SmartGuyy** [cyrilgdn/terraform-provider-postgresql#222]
Hi there,

### Terraform Version
Terraform v1.2.3

### Affected Resource(s)
resource "postgresql_grant" "database"

### Terraform Configuration Files
```hcl
resource "postgresql_database" "rds_postgres_database" {
  count             = var.postgres_enabled ? 1 : 0
  name              = replace(local.namespace, "-", "")
  owner             = postgresql_role.rds_postgres_role[0].name
  connection_limit  = -1
  allow_connections = true
}
resource "postgresql_role" "rds_postgres_role" {
  count     = var.postgres_enabled ? 1 : 0
  name      = replace(local.namespace, "-", "")
  login     = true
  password  = random_password.postgres_password[0].result
  superuser = false
}
resource "postgresql_grant" "tables" {
  count       = var.postgres_enabled ? 1 : 0
  database    = postgresql_database.rds_postgres_database[0].name
  role        = postgresql_role.rds_postgres_role[0].name
  schema      = postgresql_schema.public[0].name
  object_type = "table"
  privileges  = ["SELECT", "INSERT", "UPDATE", "DELETE", "TRUNCATE", "REFERENCES", "TRIGGER"]
}
resource "postgresql_grant" "database" {
  count       = var.postgres_enabled ? 1 : 0
  database    = postgresql_database.rds_postgres_database[0].name
  role        = postgresql_role.rds_postgres_role[0].name
  object_type = "database"
  privileges  = ["CREATE", "CONNECT", "TEMPORARY", "TEMP"]
}

resource "random_password" "postgres_password" {
  count   = var.postgres_enabled ? 1 : 0
  length  = 12
  special = false
}
resource "postgresql_schema" "public" {
  count    = var.postgres_enabled ? 1 : 0
  name     = "public"
  database = postgresql_database.rds_postgres_database[0].name
  owner    = postgresql_role.rds_postgres_role[0].name

}
```

### Debug Output

   module.xxx.postgresql_grant.database[0] will be updated in-place
  ~ resource "postgresql_grant" "database" {
        id                = "xxx"
      ~ privileges        = [
          + "TEMP",
            # (3 unchanged elements hidden)
        ]
        # (4 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.`

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
No change

### Actual Behavior
1 change at each terraform plan even after apply

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` --> apply
2. `terraform plan` --> observe unexpected change

### Important Factoids
ø

### References
https://github.com/cyrilgdn/terraform-provider-postgresql/issues/197

**Comment by pawandhiman10** [comment]
+1 
Facing the same issue. 

Expected: 
No change

Actual Behavior: 
  1. Adding grants in first terraform apply 
  2. Removing grants in second terraform apply
  3. Pattern repeats after every terraform apply

**Comment by jojinkb** [comment]
+1
This is blocking our adoption of terraform to manage our database objects. Would appreciate it if we can get an update on whether this has been picked up.

**Comment by bfox1793** [comment]
In our experience, [with this issue](https://github.com/cyrilgdn/terraform-provider-postgresql/issues/197), it doesn't actually affect the underlying grants on the DB, but the terraform state is in constant flux & makes it _seem_ like changes are happening, when they aren't. It's functionally noise, but also defeats the purpose of using terraform plans to detect drifts / changes in state.

I had trouble reproducing it on my issue, but glad to see that we have something reproducible that can be debugged & traiged.

**Comment by cyrilgdn** [comment]
@SmartGuyy Actually `TEMP` is an alternative spelling of `TEMPORARY` but it's not correctly handle in the provider, I'll probably remove it from the list of privileges for databases.

In your example, you can simply remove it as you also have `TEMPORARY` in your privileges list.

**Comment by bfox1793** [comment]
> @SmartGuyy Actually `TEMP` is an alternative spelling of `TEMPORARY` but it's not correctly handle in the provider, I'll probably remove it from the list of privileges for databases.
> 
> In your example, you can simply remove it as you also have `TEMPORARY` in your privileges list.

@cyrilgdn I think it's important to note that, while the issue of `TEMP` and `TEMPORARY` is fair, it seems there may be an actual bug in the provider here. As @yaronmahat mentioned in #197, we've seen a lot of infinite diffs when combining actual privileges with default_privileges.

**Comment by cyrilgdn** [comment]
@bfox1793 I understand, but as you mentioned there's already an issue for that so I'll close this one once `TEMP` remove as it's the initial problem for this PR.
