### ISSUE TITLE
Potential release of master?

### ISSUE THREAD

**Issue by Dombo** [cyrilgdn/terraform-provider-postgresql#239]
Hi,

This provider is great, I use it for so many things throughout my day-to-day - so nice job and thank you for your efforts building and maintaining it over the years(!).

I've noticed there's [some untagged but merged features on master/main](https://github.com/cyrilgdn/terraform-provider-postgresql/compare/4c52d3aea45a50695adf8561bbe5e8ede09488f0...6850ed91594e017a34a2c453c477fd3e0f69b4de). Is there anything standing in the way of pushing a tag so these can be consumed via the terraform registry @cyrilgdn?

Thanks

**Comment by cyrilgdn** [comment]
Hi @Dombo ,

Thanks for opening this issue and for your kind message :blush: 

[v1.17.0](https://registry.terraform.io/providers/cyrilgdn/postgresql/1.17.0) has just been released.
