### ISSUE TITLE
 Revoking public schema access not working as expected

### ISSUE THREAD

**Issue by gwkunze** [cyrilgdn/terraform-provider-postgresql#33]
Copied from hashicorp/terraform-provider-postgresql#165

### Terraform Version
```
Terraform v0.12.24
+ provider.postgresql v1.7.0
```

### Affected Resource(s)
Please list the resources as a list, for example:

 - postgresql_schema

### Terraform Configuration Files

```hcl
resource "postgresql_database" "database" {
  for_each = var.databases
  name = each.key
  template = "template1"
  lc_collate = "en_US.UTF-8"
  lc_ctype = "en_US.UTF-8"
}

// Don't allow the public role to create in the public schema
resource "postgresql_schema" "public" {
  for_each = var.databases

  database = each.key
  name = "public"
  policy {
    role = "public"
    create = false
    create_with_grant = false
    usage = false
    usage_with_grant = false
  }
}
```

### Expected Behavior

I'd expect the `public` role not to have the (default) `usage` and `create` permissions on the `public` schema

### Actual Behavior

The `public` schema still allows any user (with the `public` role) to use and create tables. Note that setting `create` and `usage` to `true` and applying, followed by setting them back to `false` and applying again does remove the permissions as expected.

### Important Factoids
Running on RDS created Postgres 12.3 instance

-----------
Just tested with both `role = "public"` and `role = ""` (since postgres seems to store ACLS for public as `""`) but the same behaviour is shown for both

-----------
Reading the code, I think there are two problems:

  1. When creating a resource, it is only granting permissions, and the code does not seem to have any functionality related to revoking implicitly granted permissions
  2. When refreshing the schema resource, while the code [reads and parses](https://github.com/terraform-providers/terraform-provider-postgresql/blob/master/postgresql/resource_postgresql_schema.go#L357) the policies, it doesn't actually do anything with them. Meaning Terraform will only compare previously set state to desired state, with the current state being completely ignored.

**Comment by icterine** [comment]
I can confirm. did not work for me as well

**Comment by cyrilgdn** [comment]
Hi @gwkunze ,

Thanks for opening this issue, I also discovered this bug recently.
As I mentioned [here](https://github.com/cyrilgdn/terraform-provider-postgresql/issues/12#issuecomment-753338496), schema policies are a bit buggy but we won't fix it as it has been deprecated in v1.11.0 (which has just been released).

To grant/revoke access on schema, you can now use the `postgresql_grant` resource.
e.g., for this [specific use case](https://registry.terraform.io/providers/cyrilgdn/postgresql/latest/docs/resources/postgresql_grant#examples):

```hcl
resource "postgresql_grant" "revoke_public" {
  database    = "test_db"
  role        = "public"
  schema      = "public"
  object_type = "schema"
  privileges  = []
}
```

I close this issue but feel free to answer/open it back if needed.

**Comment by firestrtur** [comment]
Hi,

The "policy" is Deprecated but it provided for a "*_with_grant" option.  I don't see that as a privilege in the postgresql_grant resource, is that option available?

privileges - (Required) The list of privileges to grant. There are different kinds of privileges: SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, CREATE, CONNECT, TEMPORARY, EXECUTE, and USAGE.

**Comment by cyrilgdn** [comment]
@firestrtur There's the option but not in the documentation apparently :man_facepalming: 

Resource `postgresql_grant` has a `with_grant_option` boolean.

```hcl


resource "postgresql_grant" "revoke_public" {
  database    = "test_db"
  role        = "test_role"
  schema      = "test_schema"
  object_type = "schema"
  privileges  = []

  with_grant_option = true
}
```

**Comment by firestrtur** [comment]
That worked. Thanks!

**Comment by burakovsky** [comment]
A note for users, who try to revoke public schema default access on AWS RDS - by default, PostgreSQL terraform provider creates a database using [template0](https://github.com/cyrilgdn/terraform-provider-postgresql/blob/master/postgresql/resource_postgresql_database.go#L167) although PostgreSQL uses [template1](https://www.postgresql.org/docs/9.3/manage-ag-templatedbs.html)  as default. According to [AWS documentation](https://aws.amazon.com/premiumsupport/knowledge-center/rds-postgresql-revoke-public-schema/), in Amazon RDS PostgreSQL, the owner of database template0 is `rdsadmin`, and the owner of template1 is the master user. And in this case, you can't revoke default public access using `postgresql_grant` resource as explained above. But it works if you use template1 for database creation.

Hope it will help someone who bumped with this issue, like me  :)
