### ISSUE TITLE
postgres user fails to authenticate (even when not mentioned) instead of the user provided in the provider file(?)

### ISSUE THREAD

**Issue by simonebenati** [cyrilgdn/terraform-provider-postgresql#336]
Hi there,

Thank you for opening an issue. Please provide the following information:

### Terraform Version
Terraform v1.4.6

### Affected Resource(s)
Please list the resources as a list, for example:
- resource "postgresql_database" "mydatabase"
- maybe more? (not sure)

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
I don't have anything special configured

### Debug Output
https://gist.github.com/simonebenati/aa6392f4089a3077b87bf63f4ad077e3

### Panic Output
None

### Expected Behavior
I don't understand why the postgres user pops up when i'm not using it anywhere in my code.
I think the user used to create dbs should be the one provided in the provider configuration
### Actual Behavior
The user postgres keeps popping out

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Running the postgresql tf provider against cloudnative postgresql (kubernetes operator)

### References
No

**Comment by tspearconquest** [comment]
I took a look at the log; it's difficult to say from this log; are you able to redact and share your code so it can be checked further?

**Comment by cyrilgdn** [comment]
Hi @simonebenati ,

As mentioned by @tspearconquest, it's hard to debug with the log only, I'm not sure what do you mean actually.

I close this issue but you can reopen it if you still have this issue and want to provide more details.
