### ISSUE TITLE
postgresql_grant: Error: "database": required field is not set

### ISSUE THREAD

**Issue by gws** [cyrilgdn/terraform-provider-postgresql#35]
When using the `postgresql_grant` resource, I am not able to use output from another resource in the "database" field. When I supply a string directly, it works.

### Terraform Version

Terraform: `0.13.5`
AWS provider: `3.23.0`
PostgreSQL provider: `1.11.0`

### Affected Resource(s)

- postgresql_grant

### Terraform Configuration Files
```hcl
resource "aws_rds_cluster" "this" {
  cluster_identifier              = "${var.rds_cluster_identifier}-${var.environment}"
  db_subnet_group_name            = aws_db_subnet_group.this.name
  db_cluster_parameter_group_name = aws_rds_cluster_parameter_group.this.name
  deletion_protection             = true
  engine                          = "aurora-postgresql"
  engine_mode                     = "serverless"
  engine_version                  = var.rds_engine_version
  master_username                 = "postgres"
  master_password                 = random_password.rds.result
  backup_retention_period         = var.rds_backup_retention_period
  copy_tags_to_snapshot           = true
  skip_final_snapshot             = true
  vpc_security_group_ids          = [aws_security_group.rds.id]

  scaling_configuration {
    auto_pause               = true
    min_capacity             = var.rds_min_capacity
    max_capacity             = var.rds_max_capacity
    seconds_until_auto_pause = 300
  }

  tags = var.tags
}

resource "postgresql_role" "service" {
  name                = var.rds_service_username
  login               = true
  password            = var.rds_service_password
  skip_reassign_owned = true
  skip_drop_role      = true
}

resource "postgresql_schema" "service" {
  name = "service"
}

resource "postgresql_grant" "service" {
  role        = postgresql_role.service.name
  database    = aws_rds_cluster.this.database_name
  schema      = postgresql_schema.service.name
  object_type = "schema"
  privileges  = ["ALL"]
}
```

### Expected Behavior

Terraform would apply the grant described in `postgresql_grant.service`.

### Actual Behavior

An error occurred:

```
Error: "database": required field is not set

  on ../../modules/test/main.tf line 253, in resource "postgresql_grant" "service":
 253: resource "postgresql_grant" "service" {

Error: "database": required field is not set

  on ../../modules/test/main.tf line 253, in resource "postgresql_grant" "service":
 253: resource "postgresql_grant" "service" {
```

### Steps to Reproduce

1. Configure the PostgreSQL provider to connect to a local database
2. Configure an RDS database appropriately
3. `terraform apply`

**Comment by cyrilgdn** [comment]
Hi @gws ,

Thanks for opening this issue.

I never used the `aws_rds_cluster` resource but if I read correctly the  output `database_name` is empty unless you specify the [`database_name` settings](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster#database_name).

[AWS API documentation](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBCluster.html) clearly specifies that if this parameter is not provided, it will not create a database.

>  DatabaseName
>
>    The name for your database of up to 64 alphanumeric characters. If you do not provide a name, Amazon RDS doesn't create a database in the DB cluster you are creating.
>
>    Type: String
>
>    Required: No

**Comment by gws** [comment]
@cyrilgdn Thank you for your reply and on reviewing my own report, I apologize for filing this issue. In retrospect, I'm not sure how I managed to draw the conclusion that the problem was related to this provider.

I appreciate all of your work on this!
