### ISSUE TITLE
Error checking signature: openpgp: key expired

### ISSUE THREAD

**Issue by eric-viera** [cyrilgdn/terraform-provider-postgresql#357]
What it says in the title happens when running terraform init, terraform tries to install version 1.21.0 and fails

**Comment by bceskavich** [comment]
I am seeing this as well on version 1.16.0.

**Comment by tacchino** [comment]
Saw this as well on latest Terraform release. Not a problem when I went back to 1.5.7

**Comment by beaugunderson** [comment]
also seeing this today on latest terraform; going to pin our `hashicorp/setup-terraform@v2
` workflow with this and report back:

```yaml 
  with:
    terraform_version: 1.1.7
```

**Comment by beaugunderson** [comment]
that worked 👍

**Comment by lleger** [comment]
> that worked 👍

Worked for me too.

**Comment by PhuocNguyen-IT** [comment]
Worked for me too.

**Comment by bceskavich** [comment]
Pinning our Terraform version to <= 1.5.7 worked for me as well.

**Comment by mr-andres-carvajal** [comment]
Seeing this issue in 1.15

**Comment by tcraxs** [comment]
related to this https://github.com/hashicorp/terraform/issues/33984

Workaround use terraform 1.5.7

**Comment by jrisch** [comment]
> related to this [hashicorp/terraform#33984](https://github.com/hashicorp/terraform/issues/33984)
> 
> Workaround use terraform 1.5.7
> 
> Its a bug in TF not in this provider, issue can be closed.

I'm not sure I agree in the statement above. The key used to sign the releases of this provider is outdated and should be updated. So please _do not_ close this issue.

**Comment by nikolay** [comment]
The providers need to be updated with valid keys. The MySQL provider also uses expired keys, and I won't be surprised if all others (such as RabbitMQ) suffer from the same security issue.

**Comment by AlexanderProd** [comment]
Experiencing this error in TF 1.6.0

**Comment by enricojonas** [comment]
Same here - key needs to be updated...

**Comment by nikolay** [comment]
It is sad that for nearly a week, no one can get hold of @cyrilgdn and make him fix a bunch of major providers. I feel light forking and signing the forked provider with valid keys, as I personally don't like having to downgrade.

I couldn't find an email or some contact of sorts for the maintainer to ping him.

**Comment by denisraison** [comment]
Version 1.6.1 is out and should have reverted back to ignoring the expired keys.
https://github.com/hashicorp/terraform/releases/tag/v1.6.1

**Comment by cyrilgdn** [comment]
We'll update the key on the next release.
