### ISSUE TITLE
Error checking signature: openpgp: key expired

### ISSUE THREAD

**Issue by KristjanBulic** [cyrilgdn/terraform-provider-postgresql#367]
### Terraform Version
Terraform v1.6.0
on linux_amd64

### Affected Resource(s)
All

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    digitalocean = {
      source  = "digitalocean/digitalocean"
      version = "~> 2.30.0"
    }
    postgresql = {
      source = "cyrilgdn/postgresql"
      version = "~> 1.21.0"
    }
  }
}
```

### Actual Behavior
╷
│ Error: Failed to install provider
│ 
│ Error while installing cyrilgdn/postgresql v1.21.0: error checking signature: openpgp: key expired
╵

### Steps to Reproduce
1. `terraform init`

**Comment by cyrilgdn** [comment]
I'll update the GPG key for next release but anyway it works in in v1.6.1or later as they reverted the expiration check

(cf https://github.com/hashicorp/terraform/blob/v1.6.1/CHANGELOG.md#161-october-10-2023)
