### ISSUE TITLE
error checking signature: openpgp: key expired

### ISSUE THREAD

**Issue by tarekjarrarr** [cyrilgdn/terraform-provider-postgresql#379]
terraform {
  required_providers {
   postgresql = {
      source = "cyrilgdn/postgresql"
      version = "1.21.v1betab"
    }
  }

  required_version = "~> 1.6.0"
}

╷
│ Error: Failed to install provider
│ 
│ Error while installing cyrilgdn/postgresql v1.21.1-beta.1: error checking signature: openpgp: key expired
╵

**Comment by keatmin** [comment]
What terraform version are you using ? It was mentioned [here](https://github.com/cyrilgdn/terraform-provider-postgresql/issues/367) for 1.6.0 and using 1.6.1 solved it

**Comment by cyrilgdn** [comment]
I'll update the GPG key for next release but as mentioned by @keatmin , they reverted the expiration check in v1.6.1

(cf https://github.com/hashicorp/terraform/blob/v1.6.1/CHANGELOG.md#161-october-10-2023)
