### ISSUE TITLE
openpgp: key expired

### ISSUE THREAD

**Issue by ozGithub98004** [cyrilgdn/terraform-provider-postgresql#416]
Getting this error when running` terraform init`
Terraform version 1.6.0

Installing cyrilgdn/postgresql v1.22.0...
╷
│ Error: Failed to install provider
│
│ Error while installing cyrilgdn/postgresql v1.22.0: error checking signature: openpgp: key expired

**Comment by reubenavery** [comment]
Issue still present with latest version

**Comment by radogabo** [comment]
Getting same issue with terraform init 


Initializing the backend...

Initializing provider plugins...
- Finding cyrilgdn/postgresql versions matching "~> 1.22.0"...
- Finding latest version of hashicorp/aws...
- Installing cyrilgdn/postgresql v1.22.0...
- Installing hashicorp/aws v5.45.0...
- Installed hashicorp/aws v5.45.0 (signed by HashiCorp)
╷
│ Error: Failed to install provider
│
│ Error while installing cyrilgdn/postgresql v1.22.0: error checking signature: openpgp: key expired

**Comment by psazonparalect** [comment]
Same issue here.

**Comment by Techmission2611** [comment]
any solution ?
