### ISSUE TITLE
Unable to destroy postgresql_role resource: "could not reassign owned"

### ISSUE THREAD

**Issue by conzyor34** [cyrilgdn/terraform-provider-postgresql#42]
Hello;

Here are my versions:

    $ terraform -v
    Terraform v0.14.3
    + provider registry.terraform.io/cyrilgdn/postgresql v1.11.0
    + provider registry.terraform.io/hashicorp/azurerm v2.43.0

Azure Database for Postgresql is version 11.

Here is example ```main.tf``` code:

    terraform {
      required_providers {
        azurerm = {
          source = "hashicorp/azurerm"
          version = ">= 2.21.0"
        }
        postgresql = {
          source = "cyrilgdn/postgresql"
          version = ">= 1.11.0"
        }
      }
    }
    
    provider "azurerm" {
      features {}
    }
    
    resource "azurerm_postgresql_server" "postgres" {
      name                = "conzyor34db"
      location            = "eastus2"
      resource_group_name = "test-rg"
    
      sku_name = "GP_Gen5_2"
    
      storage_mb                    = 5120
      backup_retention_days         = 7
      geo_redundant_backup_enabled  = false
      auto_grow_enabled             = false
      
      administrator_login          = "admin_user"
      administrator_login_password = "<password>"
      version                      = 11
      ssl_enforcement_enabled      = true
    }
    
    resource "azurerm_postgresql_firewall_rule" "firewall_rules" {
      name                = "my_ip"
      resource_group_name = "test-rg"
      server_name         = azurerm_postgresql_server.postgres.name
      start_ip_address    = "71.239.0.0"
      end_ip_address      = "71.239.254.254"
    }
    
    resource "azurerm_postgresql_database" "postgres" {
      name                = "my_database"
      resource_group_name = "test-rg"
      server_name         = azurerm_postgresql_server.postgres.name
      charset             = "UTF8"
      collation           = "English_United States.1252"
      depends_on          = [azurerm_postgresql_firewall_rule.firewall_rules]
    }
    
    provider "postgresql" {
      host = azurerm_postgresql_server.postgres.fqdn
      port = 5432
      database = azurerm_postgresql_database.postgres.name
      username = format( "%s@%s", azurerm_postgresql_server.postgres.administrator_login, azurerm_postgresql_server.postgres.fqdn )
      password = azurerm_postgresql_server.postgres.administrator_login_password
      sslmode = "require"
      superuser = false
    }
    
    resource "postgresql_role" "role" {
      name = "my_role"
      password = "<another password>"
      login = true
    }
    
    resource "postgresql_grant" "grant" {
      role = postgresql_role.role.name
      object_type = "database"
      database = azurerm_postgresql_database.postgres.name
      privileges = ["ALL"]
    }
This configuration creates the role and grant as expected:

    postgresql_role.role: Creating...
    postgresql_role.role: Creation complete after 2s [id=my_role]
    postgresql_grant.grant: Creating...
    postgresql_grant.grant: Creation complete after 2s [id=my_role_my_database_database]

However the provider is unable to destroy the role due to formatting of the role as ```username@host```:

    postgresql_grant.grant: Destroying... [id=my_role_my_database_database]
    postgresql_grant.grant: Destruction complete after 1s
    postgresql_role.role: Destroying... [id=my_role]
    
    Error: could not reassign owned by role my_role to admin_user@conzyor34db.postgres.database.azure.com: pq: role "admin_user@conzyor34db.postgres.database.azure.com" does not exist

Running this manually produces the same result:

    psqlhostname=> reassign owned by my_role to "admin_user@conzyor34db.postgres.database.azure.com";
    ERROR:  role "admin_user@conzyor34db.postgres.database.azure.com" does not exist

But running manually without the ```@host``` portion reassigns the objects correctly:

    psqlhostname=> reassign owned by my_role to admin_user;
    REASSIGN OWNED

### Expected Behavior
The role resource should be deleted.

### Actual Behavior
The role resource isn't deleted because PostgreSQL doesn't like the format of the destination role used in the ```reassign owned``` SQL call.

### Steps to Reproduce
1. `terraform apply`
2. `terraform destroy`

### Discussion
Is something odd about Azure Postgresql databases that they do not accept the user@host format for "reassign owned"? It's hard to imagine I'm the first person who ever tried deleting a postgresql_role resource.

**Comment by conzyor34** [comment]
Basicallly there are several authentication scenarios in Postgresql where the ```username``` specified in the provider will be in ```pgusername@<something>``` format. 

How would we feel about stripping off anything after the ```@``` when trying to use the provider's ```username``` setting in a statement that expects a role name?

**Comment by cyrilgdn** [comment]
@conzyor34 For Azure, you can specify the [database_username](https://registry.terraform.io/providers/cyrilgdn/postgresql/latest/docs#database_username) setting in the provider configuration. This should fix your problem.

```hcl
provider "postgresql" {
  host = azurerm_postgresql_server.postgres.fqdn
  port = 5432
  database = azurerm_postgresql_database.postgres.name
  username = format( "%s@%s", azurerm_postgresql_server.postgres.administrator_login, azurerm_postgresql_server.postgres.fqdn )
  database_username = azurerm_postgresql_server.postgres.administrator_login
  password = azurerm_postgresql_server.postgres.administrator_login_password
  sslmode = "require"
  superuser = false
}
```

I close this issue but feel free to comment and/or open it back if needed.

**Comment by conzyor34** [comment]
Thank you so much! I completely missed that setting in the provider options. Of course it works perfectly.
