### ISSUE TITLE
'Drop schema public cascade' Is it possible to execute this using the postgresql provider?

### ISSUE THREAD

**Issue by firestrtur** [cyrilgdn/terraform-provider-postgresql#44]
### Terraform Version
v0.14.5

### Affected Resource(s)
- postgresql_schema

### Terraform Configuration Files
```hcl
resource "postgresql_schema" "drop_public" {
  database = "testdb"
  name = "public"
  drop_cascade = true
 
 policy {
    usage = false
  }
}
```

There is a warning message that "policy" is deprecated, but postgresql_grant on object_type schema with privileges set to '[ ]' does not have a "drop_cascade" option. 

### Expected Behavior
drop public schema cascade

### Actual Behavior
What actually happened?
terraform runs without any errors, but public schema is still there

### Steps to Reproduce

1. `terraform apply`

**Comment by cyrilgdn** [comment]
Hi @firestrtur ,

Thanks for opening this issue.

`drop_cascade` field applies only for `terraform destroy` command.

There's currently no way to remove an existing schema unfortunately.

**Comment by firestrtur** [comment]
Thanks for your response.
Any plans for Data Sources to get the Schema, or Resource name then drop it?

**Comment by cyrilgdn** [comment]
@firestrtur Sorry for the response delay.

>  Any plans for Data Sources to get the Schema, or Resource name then drop it?

No it's not really possible to do that with resource or data. We cannot drop a resource that has not been created by Terraform.

To drop this schema, you could take a look at the [sql provider](https://registry.terraform.io/providers/paultyng/sql/latest/docs/data-sources/query) which allows to execute query (didn't test it) or simply a [`null_resource`](https://www.terraform.io/docs/language/resources/provisioners/null_resource.html) which can execute a query with psql for example.

I allow myself to close this issue but feel free to comment or open it back if needed.
