### ISSUE TITLE
Schema in Default Privileges is Optional

### ISSUE THREAD

**Issue by brunoroque06** [cyrilgdn/terraform-provider-postgresql#46]
Hello,

In the resource `postgresql_default_privileges`, `schema` could be optional, in order to achieve:

```sql
alter default privileges grant select on tables to $role;
```

And the counter part:

```sql
alter default privileges revoke select on tables from $role;
```

Instead of: https://github.com/cyrilgdn/terraform-provider-postgresql/blob/master/postgresql/resource_postgresql_default_privileges.go#L214 . Is there a specific reason why this is not supported? Is it to enforce the schema management on the infrastructure level? Thank you!

Best,
Bruno

**Comment by cyrilgdn** [comment]
Hi @brunoroque06 ,

Thanks for opening this issue.

You're right, I think I miss the fact that it's optional when I created this resource :thinking: .

We can try to change this behavior to make it optional, I can't promise when I'll be able to work on it though. If anyone want to give a try, it would be with pleasure :blush:
