### ISSUE TITLE
Can I also execute `.sql` scripts with this

### ISSUE THREAD

**Issue by bartekpacia** [cyrilgdn/terraform-provider-postgresql#465]
Hi there, thanks for creating and maintaining this project.

I'm new to Terraform so this question may not necessarily make sense. I'll be grateful for an answer though.

Basically, can I use this action to execute SQL scripts on my newly created databases, e.g. on DigitalOcean managed postgres?

**Comment by cyrilgdn** [comment]
Hi @bartekpacia ,

It's currently not possible with this provider, you can have a look at [https://registry.terraform.io/providers/paultyng/sql/latest/docs/data-sources/query](sql provider) that seems to support that, even if it's apparently not maintained anymore.
