### ISSUE TITLE
Error: Error granting role postgres to service_test: pq: must have admin option on role "postgres"

### ISSUE THREAD

**Issue by slamd64** [cyrilgdn/terraform-provider-postgresql#51]
Hello!

Im experiencing trouble with "postgresql_grant"

TF 0.14.6, posgresql provider 1.11.1

terraform plan output:
```
module.postgres_readonly.postgresql_grant.grant_readonly_connect will be updated in-place
  ~ resource "postgresql_grant" "grant_readonly_connect" {
        id                = "service_ro_service_test_public_table"
      ~ privileges        = [
          + "SELECT",
        ]
        # (5 unchanged attributes hidden)
    }
module.postgres_readonly.postgresql_grant.grant_readonly_sequence will be updated in-place
  ~ resource "postgresql_grant" "grant_readonly_sequence" {
        id                = "service_ro_service_test_public_sequence"
      ~ privileges        = [
          + "SELECT",
        ]
        # (5 unchanged attributes hidden)
    }
module.postgres_readonly.postgresql_grant.grant_readonly_table will be updated in-place
  ~ resource "postgresql_grant" "grant_readonly_table" {
        id                = "service_ro_service_test_public_table"
      ~ privileges        = [
          + "SELECT",
        ]
        # (5 unchanged attributes hidden)
    }
Plan: 0 to add, 3 to change, 0 to destroy.
```
But terraform apply fails with:
```
Error: Error granting role postgres to service_test: pq: must have admin option on role "postgres"
  on .terraform/modules/postgres_readonly/modules/read-only-user/main.tf line 97, in resource "postgresql_grant" "grant_readonly_table":
  97: resource "postgresql_grant" "grant_readonly_table" {
Error: Error granting role postgres to service_test: pq: must have admin option on role "postgres"
  on .terraform/modules/postgres_readonly/modules/read-only-user/main.tf line 115, in resource "postgresql_grant" "grant_readonly_sequence":
 115: resource "postgresql_grant" "grant_readonly_sequence" {
```

**Comment by cyrilgdn** [comment]
Hi @slamd64 ,

Could you provide the resources definition too (with Terraform 0.14, we don't see all the fields if they don't change)? Is Terraform connected with a superuser on the database?

These resources are updated, it means that first apply worked correctly? What did you change between both plans?

Thanks in advance.

**Comment by slamd64** [comment]
Hi! Sure. Manifest is attached.

In close words it:
- connects as DB admin and creates RO user
- connects as DB rw user (tables owner) and grants permissions for RO user

In TF 0.12 and postgresql provider 1.6 it works perfect

[main.txt](https://github.com/cyrilgdn/terraform-provider-postgresql/files/5957006/main.txt)

**Comment by cyrilgdn** [comment]
@slamd64 Out of curiosity, why don't you connect with admin too for the second point?

Is `postgres` the schema owner and `db_user` tables owner?

**Comment by slamd64** [comment]
admin owns DB itself
rw_user owns tables inside DB

**Comment by cyrilgdn** [comment]
@slamd64 But why don't grant with admin directly for tables too?

**Comment by slamd64** [comment]
Because admin is not owner of tables/sequences. To grant permissions by admin it needs to change tables/sequences owner to admin.

**Comment by cyrilgdn** [comment]
@slamd64 Sorry for the response delay (I missed the notification of your answer).

> Because admin is not owner of tables/sequences. To grant permissions by admin it needs to change tables/sequences owner to admin.

Did you try it? Normally the provider temporarily grant to admin the owners of the schema and tables/sequences for which it grants the permissions especially for that.

That's actually why you have this error, `postgres` owns the schema and the provider try to grant it to the connected user.

**Comment by cyrilgdn** [comment]
I allow myself to close this issue but feel free to comment and open it back if needed.
