### ISSUE TITLE
Error connecting to Google's CloudSQL Postgres instance using 1.11.1

### ISSUE THREAD

**Issue by tun0** [cyrilgdn/terraform-provider-postgresql#55]
Hi,

Originally we had the following in the `terraform` configuration:
```
    postgresql = {
      source  = "cyrilgdn/postgresql"
      version = "~> 1.11.0"
    }
```
 Which led to recent bump to `1.11.1`. Since that release `terraform plan` errors out when trying to connect to the psql instance.

After changing it to `version = "1.11.0", it works just fine, again.

### Terraform Version
`0.13.0`

### Affected Resource(s)
all

### Terraform Configuration Files
```hcl
provider "postgresql" {
  superuser        = false
  host             = google_sql_database_instance.db.connection_name
  scheme           = "gcppostgres"
  username         = google_sql_user.postgres.name
  password         = google_sql_user.postgres.password
  expected_version = "10.0.0"
}

resource "postgresql_grant" "account" {
  for_each    = local.db_roles
  database    = google_sql_database.db[each.value.database].name
  role        = postgresql_role.account[each.value.role].name
  schema      = "public"
  object_type = "table"
  privileges  = ["SELECT"]
}

```

### Expected Behavior
Don't show errors.

### Actual Behavior
```
Error: Error reading grant role: gcppostgres: DialTimeout not supported
Error: gcppostgres: DialTimeout not supported
Error: gcppostgres: DialTimeout not supported
```

### Steps to Reproduce
Upgrade from `1.11.0` to `1.11.1`

**Comment by ynaka81** [comment]
I was having the same issue and found it is solved with `connect_timeout = 0`.
I think the issue is gocloud does not support `connection_timeout`.

**Comment by tun0** [comment]
Ah, thanks for the tip and PR!
