### ISSUE TITLE
Error when creating postgresql_role role that already exists

### ISSUE THREAD

**Issue by totogtr** [cyrilgdn/terraform-provider-postgresql#57]
Hi,
First of all, thanks for the great work on this module.
I'm having an issue when trying to create a role that is already existing in the db. The case happens when re-applying the terraform conf on a already existing db, not when creating / initializing it for the first time.
Using postgres, this can be done catching the error using `EXCEPTION WHEN DUPLICATE_OBJECT`  procedural language for example.

Is this the expected behavior or can we work on something (a boolean parameter ?) that could be used to catch that exception ? I would be happy to contribute. Let me know if any additional info is needed in the meantime.

Cheers,
Thomas

### Terraform Version
```
Terraform v0.14.6
provider registry.terraform.io/cyrilgdn/postgresql v1.11.1
```

### Affected Resource(s)
- postgresql_role

### Debug Output
``` postgresql_role.my_role: Creating...

Error: error creating role my_role: pq: role "my_role" already exists

  on database_user_mgmt.tf line 1, in resource "postgresql_role" "my_role":
   1: resource "postgresql_role" "my_role" {
```

### Expected Behavior
What should have happened?
Terraform should have done nothing and exiting as role is already there.

### Actual Behavior
What actually happened?
Terraform exited with an error

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` on a `resource "postgresql_role" "my_role"` that is already existing in the db.

```
resource "postgresql_role" "my_role" {
  name     = "my_role"
  login    = true
  superuser = false
  replication = false
  inherit = true
  create_database = true
  create_role = false
  password = "my_password"
}
```

**Comment by totogtr** [comment]
Hi @cyrilgdn  
When you'll have some time, could you please let me know what can be done or point me in the right direction on the code to change this behavior ?
Thanks !

**Comment by cyrilgdn** [comment]
@totogtr The normal workflow would be to `terraform import` the role before so it will update it instead of trying to create it.

You can import it with:
```bash
terraform import postgresql_role.my_role my_role
```

We could add an option to ignore the creation if it already exists but then you may have a diff in next `terraform plan` if existing role does not match your definition so I'm not sure it's the right thing to do :thinking: 
(some others resources support this though when Postgres have the `IF NOT EXISTS` possibility)

**Comment by totogtr** [comment]
Thanks.
In my use case, I would like to create a role with terraform, then being able to apply again the same configuration (or with modifications unrelated to postgresql role creation). In that case I guess import would not work but I might be wrong.

I am interested in your second option and would be happy to contribute, I'll have a look at the code these days.

**Comment by cyrilgdn** [comment]
@totogtr 

> In my use case, I would like to create a role with terraform, then being able to apply again the same configuration

This should work, I'm not sure to understand.

`terraform import` is only needed if the role has been created without Terraform (manually for example) and you want to declare it in Terraform afterwards.

If the role does not exist, you can create it with Terraform and apply it again.

Does this error:
```
Error: error creating role my_role: pq: role "my_role" already exists
```
happened for a role created by Terraform?

**Comment by totogtr** [comment]
hmm I guess you're right, the error happened in a CI with a role created outside of Terraform and not imported, so it seems to be my mistake ! Thanks for your help !
