### ISSUE TITLE
PostgreSQL version: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by swoodford-clear** [cyrilgdn/terraform-provider-postgresql#65]
### Terraform Version
`Terraform v0.13.6`

### Affected Resource(s)
- postgresql

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    postgresql = {
      source = "cyrilgdn/postgresql"
    }
  }
  required_version = ">= 0.13"
}

provider "postgresql" {
  scheme          = "awspostgres"
  superuser       = false
  host            = var.host
  port            = 5432
  database        = var.root_database
  username        = var.root_username
  password        = var.root_password
  sslmode         = "require"
  connect_timeout = 10
}

resource "postgresql_role" "admin" {
  name             = "admin"
  login            = true
  password         = "theadminpassword"
  connection_limit = 100
  create_database  = true
}
```

### example.tfvars
```hcl
host          = "my-rds-db.asdf12345.us-gov-east-1.rds.amazonaws.com"
root_username = "therootuser"
root_password = "therootpassword"
root_database = "example_db"
```

### Debug Output
https://gist.github.com/swoodford-clear/ffaa75e7a414db80648d8a5d31ff1ede

### Expected Behavior
resource postgresql_role.admin created

### Actual Behavior
`Error: error detecting capabilities: error PostgreSQL version: x509: certificate signed by unknown authority`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
I'm running MacOS Mojave 10.14.6 (18G8022).
In AWS region us-gov-east-1, the only RDS Certificate authority currently available is rds-ca-2017.
I've tried installing the relevant certs from AWS to my Keychain: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html
AWS GovCloud (US-East) (Root CA-2017) root certificate for an AWS GovCloud (US) Region
AWS GovCloud (US-East) (CA-2017) intermediate certificate for an AWS GovCloud (US) Region
And the certificate bundle that contains both the intermediate and root certificates for the AWS GovCloud (US) Regions.
I've made sure they're set to Always Trust in my keychain.
I've tried alternate sslmode settings: require, disable, prefer, verify-full.  Nothing worked.
I can connect to this db using the regular psql command line.

**Comment by cyrilgdn** [comment]
Hi @swoodford-clear ,

Could you try removing the `scheme          = "awspostgres"` settings so it will use the default driver (`lib/pq`).
`awspostgres` uses Gocloud library that is supposed to simplify the connection to cloud provider but for AWS it only helps with certificates but it's not the first time someone reports problems with it.

(Gocloud is mostly useful for GCP which has a complex authentication mechanism)

**Comment by swoodford-clear** [comment]
Hi @cyrilgdn thank you so much for your quick response, removing the  `scheme = "awspostgres"` setting indeed resolved the error.
Is there any danger in omitting the scheme setting in AWS RDS instances outside of GovCloud?

**Comment by cyrilgdn** [comment]
@swoodford-clear Sorry for the response delay.

>  Is there any danger in omitting the scheme setting in AWS RDS instances outside of GovCloud?

With the standard driver, you can download the AWS certificate authority and set [`sslmode="verify-full"`](https://registry.terraform.io/providers/cyrilgdn/postgresql/latest/docs#sslmode) with [`sslrootcert`](https://registry.terraform.io/providers/cyrilgdn/postgresql/latest/docs#sslrootcert) set the downloaded ca file.

It will then assert that the server certificate is signed by AWS.

cf https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_PostgreSQL.html#PostgreSQL.Concepts.General.SSL
