### ISSUE TITLE
Failure Reading Role Privileges for Functions

### ISSUE THREAD

**Issue by borchero** [cyrilgdn/terraform-provider-postgresql#7]
When defining a `postgresql_grant` resource with `object_type = "function"`, reading the grant fails.

This is caused by the following statement: https://github.com/cyrilgdn/terraform-provider-postgresql/blob/3765f18e98cc8e8ab463a425af41d92cc3eecc4b/postgresql/resource_postgresql_grant.go#L253-L268

It creates a query with 2 parameters but the statement is provided with 3 parameters (later in the function), causing the following error:

```bash
pq: got 3 parameters but the statement requires 2
```

**Comment by cyrilgdn** [comment]
Hi @borchero ,

I forgot to close this issue (there were another one for the same problem) but this is fixed in [v1.9.0](https://github.com/cyrilgdn/terraform-provider-postgresql/blob/master/CHANGELOG.md#190-december-21-2020).
