### ISSUE TITLE
Implement view as object type support.

### ISSUE THREAD

**Issue by mkryva** [cyrilgdn/terraform-provider-postgresql#71]
Hi. Should You add `view` to object type for `postgresql_grant`?

**Comment by cyrilgdn** [comment]
Hi @mkryva ,

As mentioned in the [documentation](https://www.postgresql.org/docs/current/sql-grant.html):

> ALL TABLES also affects views and foreign tables, just like the specific-object GRANT command

Views privileges are managed like tables.

So if you create a resource like:

```hcl
resource postgresql_grant "read_only" {
  role     = "test_role"
  database = "test_db"
  schema   = "test_schema"

  object_type = "table"
  privileges  = ["SELECT"]
}
```

This will also grant `SELECT` on all views in schema `test_schema`.

If you want to also grant privileges on futures views, you need to define [default privileges](https://registry.terraform.io/providers/cyrilgdn/postgresql/latest/docs/resources/postgresql_default_privileges) for tables too.

```hcl
resource postgresql_default_privileges "read_only" {
  role     = "test_role"
  database = "test_db"
  schema   = "test_schema"

  owner       = "test_owner"
  object_type = "table"
  privileges  = ["SELECT"]
}
```
