### ISSUE TITLE
Provider installation problems

### ISSUE THREAD

**Issue by proffase** [cyrilgdn/terraform-provider-postgresql#72]
Hi there,

Thank you for opening an issue. Please provide the following information:

### Terraform Version
Terraform v0.14.9

### Terraform Configuration Files
```hcl
terraform {
  required_version = "= 0.14.9"
  required_providers {
        mypostgresql = {
            source = "registry.terraform.io/cyrilgdn/postgresql"
        }
    }
}
```

### Debug Output
```
Initializing provider plugins...
- Finding latest version of cyrilgdn/postgresql...
- Finding latest version of hashicorp/time...
- Finding latest version of hashicorp/postgresql...
- Installing cyrilgdn/postgresql v1.12.0...
- Installed cyrilgdn/postgresql v1.12.0 (self-signed, key ID 3918DD444A3876A6)
- Installing hashicorp/time v0.7.0...
- Installed hashicorp/time v0.7.0 (signed by HashiCorp)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html

Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider
hashicorp/postgresql: provider registry registry.terraform.io does not have a
provider named registry.terraform.io/hashicorp/postgresql

```

### Expected Behavior
Only "cyrilgdn/postgresql" to be installed.

### Actual Behavior
Tries to install "hashicorp/postgresql" provider which is no longer available.

Tried to switch to new Terraform version but cannot test creating of resources as provider is not installed properly.

**Comment by itspngu** [comment]
Hey! HashiCorp changed a few things up with v0.13+ so it actually does what it's expected to do, given your configuration. You can find some background info here:

https://www.terraform.io/docs/language/providers/requirements.html#source-addresses
https://www.terraform.io/docs/language/providers/requirements.html#v0-12-compatible-provider-requirements

In short, it'll import correctly if you declare it as follows:

```hcl
terraform {
  required_providers {
    postgresql = {
      source  = "cyrilgdn/postgresql"
      version = ">=1.12.0"
    }
  }
}
```

The provider does state that it requires Terraform >= 0.13, and I'm not sure if making changes to get compatibility with the <= 0.12 format would help in this case. New to this myself.

**Comment by proffase** [comment]
Thanks. It works of I comment out remote git module instance. However, if I have a call for a remote module, which creates "postgresql_*" resources, it fails again with error on "terraform init":

```
Initializing provider plugins...
- Finding latest version of hashicorp/time...
- Reusing previous version of cyrilgdn/postgresql from the dependency lock file
- Finding latest version of hashicorp/postgresql...
- Installing cyrilgdn/postgresql v1.12.0...
- Installed cyrilgdn/postgresql v1.12.0 (self-signed, key ID 3918DD444A3876A6)
- Installing hashicorp/time v0.7.0...
- Installed hashicorp/time v0.7.0 (signed by HashiCorp)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html

Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider
hashicorp/postgresql: provider registry registry.terraform.io does not have a
provider named registry.terraform.io/hashicorp/postgresql

If you have just upgraded directly from Terraform v0.12 to Terraform v0.14
then please upgrade to Terraform v0.13 first and follow the upgrade guide for
that release, which might help you address this problem.

Did you intend to use cyrilgdn/postgresql? If so, you must specify that source
address in each module which requires that provider. To see which modules are
currently depending on hashicorp/postgresql, run the following command:
    terraform providers
```

The code I use is something like follows:
```hcl
terraform {
  required_providers {
    postgresql = {
      source  = "cyrilgdn/postgresql"
      version = ">=1.12.0"
    }
  }
}

provider "postgresql" {
  host      = var.db_host
  username  = var.db_user
  password  = var.db_password
  superuser = false
}

module "tf14_schema_and_role" {
  source  = "git::bitbucket.org:teamname/tf-module-postgres.git?ref=tf14"

  provider = postgresql
  .....
```

I tried to rename provider from postgresql to xpostgresql, use alias in provider configuration and <PROVIDER>.<ALIAS> in "provider" meta argument, but still "terraform provider" wants hashicorp version:

```
$ terraform providers

Providers required by configuration:
.
├── provider[registry.terraform.io/cyrilgdn/postgresql] >= 1.12.0
└── module.tf14_schema_and_role
    ├── provider[registry.terraform.io/hashicorp/time]
    └── provider[registry.terraform.io/hashicorp/postgresql]
```

I see that terraform documents tell about using "provider" meta argument in resources, not in remote module call. Does that mean module should be locked to 3rd-party provider or are there any ideas how to avoid that?

**Comment by daemon2010** [comment]
Same here

**Comment by itspngu** [comment]
The configuration you're using needs fixing in two places, the `providers` block of the portion in your root module that imports the remote one, and the provider setup in the imported `git::bitbucket.org:teamname/tf-module-postgres` module itself.

> ```terraform
> terraform {
>   required_providers {
>     postgresql = {
>       source  = "cyrilgdn/postgresql"
>       version = ">=1.12.0"
>     }
>   }
> }
> 
> provider "postgresql" {
>   host      = var.db_host
>   username  = var.db_user
>   password  = var.db_password
>   superuser = false
> }
> 
> module "tf14_schema_and_role" {
>   source  = "git::bitbucket.org:teamname/tf-module-postgres.git?ref=tf14" # <- needs to be updated
> 
>   provider = postgresql # <- incorrect syntax
>   .....
> ```

I can't see what the remote module does, but odds are it uses the deprecated syntax too. If you don't want to rely on [implicit default provider inheritance](https://www.terraform.io/docs/language/modules/develop/providers.html#implicit-provider-inheritance), using a [proxy provider configuration block](https://www.terraform.io/docs/language/modules/develop/providers.html#proxy-configuration-blocks) in the external module should solve it - try something along the lines of:

```hcl
# git::bitbucket.org:teamname/tf-module-postgres

terraform {
  required_providers {
    postgresql = {
      source  = "cyrilgdn/postgresql"
      version = ">=1.12.0"
    }
  }
}

# Note how nothing is configured here, the configuration is supplied by whoever imports the module
provider "postgres" {
  alias = "a_proxied_provider"
}

resource "postgresql_database" "db1" {
  provider = postgresql.a_proxied_provider
  name = "db1"
  owner = "postgres"
}
```

Configuring providers on the root level while having version constraints a "proxy" provider in child modules is the canonical way to work with modules now. So, in your root module you'll need something like this:

```hcl
# main.tf

terraform {
  required_providers {
    postgresql = {
      source  = "cyrilgdn/postgresql"
      version = ">=1.12.0"
    }
  }
}

provider "postgres" {
  alias = "pg_one_of_many_but_this_is_mine"

  host      = var.db_host
  username  = var.db_user
  password  = var.db_password
  superuser = false
}

module "tf14_schema_and_role" {
  source  = "git::bitbucket.org:teamname/tf-module-postgres.git?ref=tf14"

  # Note the different syntax! https://www.terraform.io/docs/language/modules/develop/providers.html#passing-providers-explicitly
  providers = {
    postgres.a_proxied_provider = postgres.pg_one_of_many_but_this_is_mine
  }

  # [...]
}
```

**Comment by cyrilgdn** [comment]
Thanks @itspngu for your help on this issue.

@proffase I allow myself to close the issue as last @itspngu anwser is right but feel free to comment or open it back if needed.
