### ISSUE TITLE
Terraform 0.15 crashes if engine version is empty string

### ISSUE THREAD

**Issue by fdw** [cyrilgdn/terraform-provider-postgresql#77]
Hi there,

Thank you for opening an issue. Please provide the following information:

### Terraform Version
`0.15.0`

### Affected Resource(s)
- provider

### Terraform Configuration Files
```hcl
provider "postgresql" {
  host = <blah>
  port = 5432
  database = "postgres"
  username = <user>
  password = <password>
  sslmode = "require"
  connect_timeout = 60
  expected_version = ""
  superuser = false
}
```

### Debug Output
I could not find relevant debug output

### Panic Output
No panic, at least

### Expected Behavior
Nothing should have happened if the engine version is empty and no resources are defined.

### Actual Behavior
Even if there are no resources for this provider, with an empty version, I get the unhelpful error:
`invalid version (""): strconv.ParseUint: parsing "": invalid syntax`

### Steps to Reproduce
With the above config, run `terraform plan`

**Comment by cyrilgdn** [comment]
Hi,

Thanks for opening this issue. 

We can fix it but actually there's no point to set this an empty string for this value, and I'm thinking about deprecating it (or at least removing it from the documentation) as it's only used while creating the connection string to know if Postgresql version is >= 9.0.0.

Unless you use an older version, you can remove the `expected_version` setting.

**Comment by fdw** [comment]
Works perfectly without that setting, so I'm closing this. Thank you!
