### ISSUE TITLE
How to inject properly password to connect into the database?

### ISSUE THREAD

**Issue by dcuenot** [cyrilgdn/terraform-provider-postgresql#8]
Hello,

Currently, if I want to connect to my database, I have to define login and password directly in my provider.
```
provider "postgresql" {
  host            = "dev-postgresql.postgres.database.azure.com"
  port            = 5432
  database        = "my-db"
  username        = "svc@dev-postgresql"
  password        = "my-password"
  sslmode         = "require"
  connect_timeout = 15
  superuser = false
}
```

I also discovered we cannot define variable in the provider declaration :( 
From your PoV is there a way to inject login and password in another way? Because my need is to be able to commit my terraform on a git repository, and with login/password in clear, it is not a good practise :( 

Thanks in advance for your help
Regards
Damien

**Comment by quixoticotech** [comment]
Are you using local command line or CI/CD platforms?

Currently, I use Hashicorp Vault to securely inject the passwords via code, but that only works in certain implementations that work side by side with Vault.

**Comment by dcuenot** [comment]
Yes I'm using my local CLI, and I want to use Gitlab-CI also.

@quixoticotech do you have an example to show me with Hashicorp Vault?

**Comment by cyrilgdn** [comment]
Hi @dcuenot ,

There's multiple way to do that (I probably don't know all of them):

## Environment variables

It's not documented (and it should be :man_facepalming: ) but all of the provider settings can be set with environment variables

e.g.:
```bash
export PGHOST=localhost
export PGPORT=5432
export PGUSER=postgres
export PGPASSWORD=postgres
[...]
```

## Terraform variables

> I also discovered we cannot define variable in the provider declaration :(

I think you should be able to use TF variables too, e.g.:
```hcl
variable "host" {
  default = "localhost"
}

variable "password" {
  default = "adm"
}

variable "port" {
  default = 55432
}

provider "postgresql" {
  host     = var.host
  port     = var.port
  password = var.password
  sslmode  = "disable"
}

resource postgresql_database "test" {
  name = "test"
}
```
 I can run this against a Postgresql server run with: 
```bash
docker run --rm -e POSTGRES_PASSWORD=adm -e PGPORT=55432 --network=host postgres
```

Then you can use a Terraform variables file or environment variables too (``TF_VAR_host``, ...)

## Data for external sources

You can use Terraform data to retrieve secrets for external sources (Vault, AWS secrets manager, files, etc...)

For AWS secrets manager for example, it could be something like:
```hcl
data "aws_secretsmanager_secret" "postgres_password" {
  name = "postgres_password"
}
data "aws_secretsmanager_secret_version" "postgres_password" {
  secret_id = data.aws_secretsmanager_secret.postgres_password.id
}

provider "postgresql" {
   [...]
   password = data.aws_secretsmanager_secret_version.postgres_password.secret_string
}
```

So you can use data for the secrets provider you want. I never used Vault yet, but there are [Terraform datas](https://registry.terraform.io/providers/hashicorp/vault/latest/docs/data-sources/generic_secret) in Vault provider to retrieve secrets.

In my company we also already used the [sops provider](https://registry.terraform.io/providers/carlpett/sops/latest/docs/data-sources/external) to retrieve secrets from local encrypted files with [sops](https://github.com/mozilla/sops)

**Comment by cyrilgdn** [comment]
I close this issue but feel free to comment or open it back if needed.
