### ISSUE TITLE
Error: could not check if database exists: dial tcp: lookup <<Cluster_host>> on 7.7.7.7:53: no such host

### ISSUE THREAD

**Issue by prashanthparsi** [cyrilgdn/terraform-provider-postgresql#91]
Hi there,

Thank you for opening an issue. Please provide the following information:

Trying to create the RDS aurora postgres cluster and then once the cluster is created, trying to create the schema on the postgres. So, both has to happen together. Cluster creation + Schema Creation. I tried all the options suggested in this but still getting error. https://github.com/hashicorp/terraform-provider-postgresql/issues/2

When running plan, i get below error - 
Error: could not check if database exists: dial tcp: lookup <<rds host>> on 7.7.7.7:53: no such host

Note: first time it worked, when I am trying again it started sending this errors. Worked only first time :(

Please help. I need this to be working ASAP.

### Terraform Version
terraform -v
Terraform v0.12.26
+ provider.aws v3.37.0
+ provider.null v3.1.0
+ provider.postgresql v1.7.2
+ provider.random v3.1.0

### Affected Resource(s)
Please list the resources as a list, for example:
- postgresql_schema

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```
//Postgres Provider - For more information -> https://registry.terraform.io/providers/cyrilgdn/postgresql/latest/docs
provider "postgresql" {
  host             =  module.aurora.this_rds_cluster_endpoint  
  port             = module.aurora.this_rds_cluster_port       
  database         = module.aurora.this_rds_cluster_database_name
  username         = data.aws_ssm_parameter.username.value 
  password         = data.aws_ssm_parameter.password.value
  superuser        = false 
  expected_version = "12"
}

resource "postgresql_role" "test_role" {
  name               = data.aws_ssm_parameter.schema_name.value
  encrypted_password = true
  login              = true
  password           = data.aws_ssm_parameter.schema_password.value
  create_role        = true 
  superuser          = false
}

resource "postgresql_schema" "test_schema" {
  name          = data.aws_ssm_parameter.schema_name.value
  if_not_exists = true
  owner         = data.aws_ssm_parameter.schema_name.value
  drop_cascade = true
}

resource "postgresql_grant" "test_grant_privileges" {
  database    = module.aurora.this_rds_cluster_database_name
  role        = postgresql_role.test_role.name 
  schema      = data.aws_ssm_parameter.schema_name.value
  object_type = "database"
  privileges  = ["ALL"] 
}
```

### Debug Output
Error: could not check if database exists: dial tcp: lookup <<rds host>> on 7.7.7.7:53: no such host

### Expected Behavior
Clusters and Schema should be created.

### Actual Behavior
Plan is failing with below error ->
Error: could not check if database exists: dial tcp: lookup <<rds host>> on 7.7.7.7:53: no such host

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init`
2.  `terraform plan `

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
Tried the solutions from here -> https://github.com/hashicorp/terraform-provider-postgresql/issues/2
None of them working.
Please help

**Comment by cyrilgdn** [comment]
Hi @prashanthparsi ,

Thanks for opening this issue.

You are using an outdated version of the provider which was trying to connect to the server too early (so before it exists if you create everything at once). hashicorp/terraform-provider-postgresql#2 has been fixed in v1.10 (but you should use the latest v1.13 which fix a performance problem introduce by the v1.10 fix).

Could you update your provider version and see if it fixes your problem?

**Comment by prashanthparsi** [comment]
Thanks for the response @cyrilgdn 
Are you suggesting me to upgrade the terraform version from v0.12.26 to v1.13 to fix the issue? Please let me know.

**Comment by prashanthparsi** [comment]
@cyrilgdn  this is what I get with the postgres provider 1.13

```No provider "postgresql" plugins meet the constraint "~> 1.13".```

The version constraint is derived from the "version" argument within the
provider "postgresql" block in configuration. Child modules may also apply
provider version constraints. To view the provider versions requested by each
module in the current configuration, run "terraform providers".

To proceed, the version constraints for this provider must be relaxed by
either adjusting or removing the "version" argument in the provider blocks
throughout the configuration.

**Comment by prashanthparsi** [comment]
I tried with ```1.13.0``` and ```1.13``` and I get below errors

No provider "postgresql" plugins meet the constraint "1.13.0".
The version constraint is derived from the "version" argument within the
provider "postgresql" block in configuration. Child modules may also apply
provider version constraints. To view the provider versions requested by each
module in the current configuration, run "terraform providers".

To proceed, the version constraints for this provider must be relaxed by
either adjusting or removing the "version" argument in the provider blocks
throughout the configuration.

I am on terraform ```Terraform v0.12.26```

**Comment by cyrilgdn** [comment]
@prashanthparsi Sorry I missed that you are using v0.12.x of Terraform.

Since the release of Terraform 0.13, the "official" `postgresql` provider, i.e.: the one [hosted by Hashicorp](github.com/terraform-providers/terraform-provider-postgresql/) cannot be updated anymore.

That's why the repository is now archived and you have to open the issue here (as I was the maintainer of the old one).

So you need either to:
- (**recommended**) Upgrade to Terraform 0.13.x or above (current version is 0.15.x) and use the new [Terraform registry](https://www.terraform.io/upgrade-guides/0-13.html#explicit-provider-source-locations) with:
 ```hcl
terraform {
  required_providers {
    postgresql = {
      source  = "cyrilgdn/postgresql"
      version = ">=1.13"
    }
  }
}
```
- Or manually download the latest version of the Provider here: https://github.com/cyrilgdn/terraform-provider-postgresql/releases/tag/v1.13.0

**Comment by prashanthparsi** [comment]
Got the same issue even after running the terraform with v0.13

```
Error: could not start transaction: dial tcp: lookup use1-dev-em-database.cluster-cvjgutteaoim.us-east-1.rds.amazonaws.com on 7.7.7.7:53: no such host
```

```
terraform -v
Terraform v0.13.7
+ provider registry.terraform.io/cyrilgdn/postgresql v1.13.0
+ provider registry.terraform.io/hashicorp/aws v3.42.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

Your version of Terraform is out of date! The latest version
is 0.15.4. You can update by downloading from https://www.terraform.io/downloads.html
```

```
terraform providers

Providers required by configuration:
.
├── provider[registry.terraform.io/cyrilgdn/postgresql] >= 1.13.*
├── provider[registry.terraform.io/hashicorp/aws]
└── module.aurora
    ├── provider[registry.terraform.io/hashicorp/random] >= 2.2.*
    └── provider[registry.terraform.io/hashicorp/aws] >= 2.45.*
Providers required by state:
    provider[registry.terraform.io/cyrilgdn/postgresql]
    provider[registry.terraform.io/hashicorp/aws]
    provider[registry.terraform.io/hashicorp/random]
```


Any other thoughts? I am running this from dev machine as well as from Jenkins. The TF scripts will also create the RDS clusters and then PG schemas. Do I need to allow my local machine IP and Jenkins IP to the Security Group of RDS cluster for it to work??

**Comment by cyrilgdn** [comment]
> Got the same issue even after running the terraform with v0.13

@prashanthparsi  At least the error message is clearer, and it's clearly not linked to the provider.

> Do I need to allow my local machine IP and Jenkins IP to the Security Group of RDS cluster for it to work??

Maybe but it's not the main problem here, your DNS server is not able to resolve the RDS server name `use1-dev-em-database.cluster-cvjgutteaoim.us-east-1.rds.amazonaws.com`, hence the error `no such host`.

I guess the cluster is not publicly accessible and this server name is only resolvable and accessible from within the VPC.
You can try to connect to the database with `psql`, you'll have the same error: `psql -h 
use1-dev-em-database.cluster-cvjgutteaoim.us-east-1.rds.amazonaws.com -U postgres -d postgres` (or replace `postgres` by the database admin user).

You can check https://aws.amazon.com/premiumsupport/knowledge-center/aurora-private-public-endpoints/

I allow myself to close this issue as it's not a problem of this provider but feel free to comment or open it back if needed.
