### ISSUE TITLE
Unable to authenticate by passing the password as reference to module/resource outputs.

### ISSUE THREAD

**Issue by mustafa89** [cyrilgdn/terraform-provider-postgresql#97]
### Terraform Version
 terraform --version                                                                                                          ─╯
Terraform v1.0.0
on linux_amd64
+ provider registry.terraform.io/cyrilgdn/postgresql v1.13.0
+ provider registry.terraform.io/hashicorp/aws v3.38.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

### provider version
```hcl
terraform {
  required_providers {
    postgresql = {
      source  = "cyrilgdn/postgresql"
      version = "1.13.0"
    }
  }
}
```

### Terraform Configuration Files
```hcl
provider "postgresql" {
  scheme   = "awspostgres"
  host     = module.rds.db_instance_address
  port     = module.rds.db_instance_port
  database = module.rds.db_instance_name
  username = module.rds.db_instance_username
  password = module.rds.db_instance_password
  superuser = false
  # sslmode         = "require"
  connect_timeout = 15
}
```

### Expected Behavior
- Database should connect.

### Actual Behavior
```hcl
╷
│ Error: error detecting capabilities: error PostgreSQL version: pq: password authentication failed for user "xyzabc"
│
│
╵
```

### Steps to Reproduce
- Create an RDS instance using the terraform rds module. https://github.com/terraform-aws-modules/terraform-aws-rds
-  Try to connect to it using this provider.
- Pass the module outputs directly as shown above. 
- `terraform apply`

In the provider config, the referencing of the password does not work. Neither from the module output nor the aws_secret_manager direct reference. 

Works perfectly with the same password if it is passed in plain text like so. "asdasd12313123"
keeping everything else (db, host, port references) as shown above the same.

**Comment by mustafa89** [comment]
Would be great to have an update here. thanks :)

**Comment by mustafa89** [comment]
Okay, I solved this. You have to use the secret manager here differently than you would when for example populating ECS env vars. creating a data source for the secret version and then referencing it as the secret_string worked.

closing.

**Comment by mustafa89** [comment]
Thanks for the great work btw. :)

**Comment by cyrilgdn** [comment]
@mustafa89 Sorry for the delay, glad that you solved your issue.
